void update()
{
	puddle_velocities[gid].y -= 0.5 * puddle_deltaTime;
	puddle_positions[gid].xyz += puddle_velocities[gid].xyz * puddle_deltaTime;

	if (puddle_positions[gid].y < -4)
	{
		if (puddle_floorHit[gid] == 0)
			puddle_lifetimes[gid] = 1;
		puddle_positions[gid].y = -4;
		puddle_floorHit[gid] = 1.0;
	}
}

void main()
{
	uint gid = gl_GlobalInvocationID.x;

	if (puddle_lifetimes[gid] <= 0)
		return;

	puddle_lifetimes[gid] -= 2 * puddle_deltaTime;

	if (puddle_lifetimes[gid] <= 0)
	{
		puddle_lifetimes[gid] = -1;
		atomicCounterDecrement(puddle_aliveParticles);

		return;
	}
	
	update();
}