void main()
{
	uint gid = gl_GlobalInvocationID.x;

	if (virus_lifetimes[gid] <= 0)
		return;

	virus_lifetimes[gid] -= 0.025;

	if (virus_lifetimes[gid] <= 0)
	{
		virus_lifetimes[gid] = -1;
		atomicCounterDecrement(virus_aliveParticles);

		return;
	}
	
	virus_positions[gid].xz = vec2(	virusAnimationRadius * sin(radians(virusAnimationAngle)),
									virusAnimationRadius * cos(radians(virusAnimationAngle)));

	virusPos[0] = virus_positions[gid];

	virus_positions[gid].w = virusAnimationAngle;
}