void main()
{
	uint gid = gl_GlobalInvocationID.x;

	if (atomicCounter(aliveParticles) < testuni)

	if (lifetimes[gid] <= 0)
	{
		if (atomicCounterIncrement(emissionAttempts) < 1)
		{
			atomicCounterIncrement(aliveParticles);

			lifetimes[gid] = 1.0;
			positions[gid] = vec4(0);
			velocities[gid].xy = vec2(	snoise(vec2(gid,gid*gid)),
										snoise(vec2(gid+3,gid+4*gid))) * 0.001;
			colors[gid] = vec4(0.9,0.1,0.1,1);
		}
	}
}