void main()
{
	uint gid = gl_GlobalInvocationID.x;

	if (rocket_lifetimes[gid] <= 0)
		return;

	rocket_lifetimes[gid] -= 0.025;

	if (rocket_lifetimes[gid] <= 0)
	{
		atomicCounterDecrement(rocket_aliveParticles);
		uint index = atomicCounterIncrement(rdpLast);
		rocketDeathPos[index] = rocketpositions[gid];
		return;
	}

	rocketpositions[gid].xyz += rocket_velocities[gid].xyz;
	rocketpositions[gid].a = 1;
}